// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cymgmhgvdjnbnwxgkudq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5bWdtaGd2ZGpuYm53eGdrdWRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2NjI3NzcsImV4cCI6MjA1MTIzODc3N30.R9xXcNsH67UvbZNnzyd3K2-okI4TuXBGrrF61wJqeXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);